/* Roboto Regular - Base64 */
var ROBOTO_FONT =
"AAEAAAARAQAABAAQR0RFRrRCsIIAAAEcAAAAHEdQT1O3fY8lAAABJAAAAGRHU1VC7E6k" +
"AAABnAAAACBPUy8yTg9xkgAAAcAAAAAIZ2FzcP//AAAB0AAAAAhnbHlmY6rHAAAB4AAA" +
"AwxoZWFkFz8HAAAB/AAAADZoaGVhC2oC5wAAAkgAAAAkaG10eI8AAQAAAmAAAAAAbG9j" +
"YQBOAAACZAAAABxtYXhwAA4AHAAABmAAAAgBuYW1lF6kAAAZ4AAABJXBvc3QAAwAAAAZ0" +
"AAAACnByZXAAAAAIAAAADAAAAAQAAAABAAD//wADAAEAAAAA";
